### PR TITLE
Simple maintenance improvements

### PR DESCRIPTION
**Pull request by a1346054**
Review comments are very welcome, I can rework the PR if needed.

### CODE REVIEW

**Comment by shundhammer** [comment]
Thank you for your contribution.

Please move out that "fix shellcheck warnings" commit into a separate pull request; that one needs a separate (and probably intensive) discussion. It should be easy enough to move that commit out for the time being with `git rebase -i 'HEAD~8'` to rearrange the commits.

The other commits look perfectly alright to me, so reviewing and merging them will be quick and easy. 
I especially welcome the typo fixes; they go unnoticed much too easily. ;-)

**Comment by a1346054** [comment]
Removed the commit with shellcheck fixes from this PR and created a new PR for it in #179

**Review by shundhammer — APPROVED** [review]
LGTM

**Comment by shundhammer** [comment]
Thanks for taking the time for this!

**Pull request merged**
