### PR TITLE
Add debian packaging (suitable for debocker/auto-debocker)

### PR DESCRIPTION
**Pull request by stdedos**
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>

### CODE REVIEW

**Comment by stdedos** [comment]
I don't know if you'd be interested, but it works. Hopefully 😅 

Here's an example artifact: [qdirstat_1.7.1-22_amd64.deb.zip](https://github.com/shundhammer/qdirstat/files/6811777/qdirstat_1.7.1-22_amd64.deb.zip)
(Just remove the extension)

**Comment by shundhammer** [comment]
I just removed that directory just a couple of days ago: It was horrendously outdated, and it was not at all clear for what distributions it would even work. It was just old cruft. It was not useful for _anybody_. And worse, it was for building with the old and even more horrendously outdated Qt4.

Similarly, I never added the .spec files for building RPMs: For each and every distribution, it would need a different one; because the dependencies were always different, because every distributor uses different package names; and because it tends to be different even between different versions even within the same distributor.

So, sorry, no, those files need to remain with the respective distribution. It doesn't scale at all, much less as more and more of those for different distributions begin to accumulate.

**Comment by shundhammer** [comment]
What is similarly bad is the fact that there is no way I could possibly do any meaningful maintenance for any of that, so bit rot tends to set in very early. I'd rather remain honest and not pretent to provide any of those distribution-related build instructions.

**Comment by shundhammer** [comment]
The .spec files for openSUSE can be found here:

- stable: https://build.opensuse.org/package/show/home:shundhammer:qdirstat-stable/qdirstat
- latest git: https://build.opensuse.org/package/show/home:shundhammer:qdirstat-git/qdirstat

For Red Hat / Fedora they are different, of course; despite also building RPMs.

**Pull request closed without merging**
