### PR TITLE
Qt5 / Qt6 / Mac OS X Support

### PR DESCRIPTION
**Pull request by gamecreature**
Added Qt6 support with backward compatibility to Qt5. (Fixed som Mac? specific issues).
I didn't test this code base with Qt4. So please do so if possible. 

- Added combined Qt5, Qt6 support (I didn't test it  with Qt4, but is should work).
- Tested with Qt 5.15.2, Qt 6.2.4 Mac OS X (Mac OS Montery)
- Renamed the Qt4Compat.h to QtCompat.h. This file used for Qt4, Qt5 and Qt6 compatibility.
- Converted endl to Qt::endl to fix issues on Mac OS X
- onEnterEvent signature change in Qt6, QEnterEvent / QEvent

### CODE REVIEW

**Comment by shundhammer** [comment]
Thank you, but no: This `Qt::endl` is something that I don't want in my code. The Trolls gave every Qt programmer the finger when they introduced that; they should have known that it causes tons of breakages all over every Qt program. Yet they still did it.

On the long run, I will completely replace the logger with something that does not put me at the mercy of the Trolls. But that will take until Qt6 will be mainstream; right now, it causes a mess. The way they introduced that completely incompatible change that breaks **every** program using Qt is an outrage.

And, worse, they managed to break compatibility with older versions; so you can choose to compile against Qt5/Qt4 _or_ Qt6.

See also https://github.com/shundhammer/qdirstat/blob/master/src/src.pro#L32-L45

**Comment by gamecreature** [comment]
@shundhammer I totally understand your point of view.  
As author of the edbee library (https://github.com/edbee/edbee-lib), the qt changes there were do-able, but I really don't understand some of the choices the authors (Trolls as you call them ;-) ) made.. 
The code now contains several ugly defines/workarounds to fix the backwards compatibility. (Though as a library I think I also should serve the newer versions). 
I saw your project and liked it. I just did this qt-6 migration so I thought I could contribute to it this way. 
No problem for not using this pull request, as I said earlier, I understand your point of view. 
Agains thanks you for the tool!

**Comment by shundhammer** [comment]
_Trolls_ as the traditional name for _TrollTech_ people, the original company behind Qt. That's their common name in the Open Source scene, and IIRC they have been using that themselves. Just to clarify. ;-)

**Comment by shundhammer** [comment]
Thank you for your efforts; it's really appreciated.

But this particular problem with their incompatible changes forcing ugly stuff like that `Qt::` namespace specifier for something as trival as the common C++ `endl` made me fume back when I first saw that change in Qt starting with Qt 5.15: Now it doesn't integrate seamlessly anymore, code has to be actively uglified to prevent compiler warnings and errors. And that's a no-go for me. Code has aesthetics, and they are being destroyed by stuff like that. None of that is your fault, of course. ;-)

So what I intend to do is to get rid of that entirely: The new logger will be using STL ostreams with the _standard_ `endl` which then will be used by default with a `using std::endl` statement. Being force to use a `Qt::` namespace specifier violates one principle that usually Qt follows religiously: Making code well readable and obvious, not forcing somebody reading it through tons of boilerplate stuff and syntactic noise.

The QDirStat logger is working pretty standalone anyway; what's missing is some tons of overloads for common Qt types, starting with the omnipresent `QString`. It's not exactly rocket science.

**Comment by shundhammer** [comment]
True Qt6 integration will also come at some point in the future, but right now most Linux distros (and probably BSD as well) are still heavily shipping and using Qt5. At that point, maybe Qt4 support will also be dropped, and there will probably be a clear cut; QDirStat V2.0 probably. It's still some time away, though.

**Comment by a17r** [comment]
How about now?

**Comment by shundhammer** [comment]
Right now I am very busy with [YQPkg](https://github.com/shundhammer/yqpkg).

**Pull request closed without merging**
