### PR TITLE
README/BuildEnvironment: Note for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by stdedos**

### CODE REVIEW

**Comment by shundhammer** [comment]
I don't understand that note. In what way is Ubuntu 16.04 different from earlier or later versions with that?

**Comment by stdedos** [comment]
I have never compiled qtX applications myself (until now).

Following the build instructions, I get:
```bash
$ qmake
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
```

I haven't installed `qt4-dev`, so, it is weird to me why would `qmake` not "somehow" default to `qt5` tools (that I installed as part of the build instructions)

**Comment by shundhammer** [comment]
Well, then you _did_ have some Qt 4 development related packages installed. You can check which with `dpkg -S $(which qmake)`.

Anyway, since not even I understood that note, it's misleading, so this does not improve the document.

**Comment by stdedos** [comment]
```bash
$  dpkg -S $(which qmake)
qtchooser: /usr/bin/qmake
```

I wouldn't say I have.

**Pull request closed without merging**
